docker/cron/Dockerfile, docker/cron/crontabs/root, docker/cron/docker-entrypoint.sh, docker/cron/logrotate.conf, docker/cron/logrotate.d/genova, docker/cron/periodic/15min/genova_docker_cleanup, docker/cron/scripts/docker_cleanup.sh
=> [#69] Fix cron not work

.circleci/config.yml, README.md, app/workers/github/deploy_worker.rb, lib/genova/app/client.rb, lib/genova/client.rb, lib/genova/code_manager/git.rb, lib/genova/docker/client.rb, lib/genova/ecs/client.rb, lib/genova/slack/bot.rb, lib/genova/slack/command/deploy.rb, lib/genova/slack/util.rb, lib/tasks/genova.thor, spec/lib/genova/app/client_spec.rb, spec/lib/genova/client_spec.rb, spec/lib/genova/docker/client_spec.rb, spec/lib/genova/ecs/client_spec.rb, spec/lib/genova/slack/bot_spec.rb, spec/lib/genova/slack/util_spec.rb, spec/rails_helper.rb, spec/workers/github/deploy_worker_spec.rb
`Genova::Git::RepositoryManager` -> `Genova::CodeManager::Git` に変更。
#54
=> [#54] Refactor

lib/genova/client.rb, lib/genova/config/validator/deploy_config.json, lib/genova/ecs/client.rb, lib/genova/ecs/deployer/run_task/client.rb, lib/genova/ecs/deployer/scheduled_task/client.rb, lib/genova/ecs/deployer/scheduled_task/target.rb, lib/genova/ecs/deployer/service/client.rb, spec/lib/genova/ecs/deployer/service/client_spec.rb
=> [#26] Add service options

lib/tasks/genova.thor
=> [#93] Fix encrypt failure

app/models/deploy_job.rb, app/workers/github/retrieve_branch_worker.rb, app/workers/slack/deploy_cluster_worker.rb, app/workers/slack/deploy_target_worker.rb, app/workers/slack/deploy_worker.rb, lib/genova/client.rb, lib/genova/code_manager/git.rb, lib/genova/slack/bot.rb, lib/genova/slack/command/redeploy.rb, lib/genova/slack/history.rb, lib/genova/slack/request_handler.rb, lib/genova/slack/util.rb, lib/tasks/genova.thor, spec/lib/genova/slack/util_spec.rb, spec/workers/github/retrieve_branch_worker_spec.rb, spec/workers/slack/deploy_cluster_worker_spec.rb, spec/workers/slack/deploy_target_worker_spec.rb
=> [#97] Add alias

lib/genova/ecr/client.rb, lib/genova/version.rb
=> [#164] Fix ECR repository describe failed

lib/genova/command/executor.rb, lib/genova/docker/client.rb, lib/genova/exceptions.rb, lib/genova/version.rb, spec/lib/genova/command/executor_spec.rb, spec/lib/genova/docker/client_spec.rb
#167
```
docker-compose down
git pull
docker-compose up
```
=> [#167] Fix build kit build error

lib/genova/ecs/client.rb, lib/genova/ecs/deployer/scheduled_task/target.rb, lib/genova/version.rb
https://github.com/metaps/genova/issues/188
=> Fix private method warn called for nil:NilClass

app/workers/base_worker.rb, app/workers/github/retrieve_branch_watch_worker.rb, app/workers/github/retrieve_branch_worker.rb, app/workers/slack/command_receive_worker.rb, app/workers/slack/deploy_cluster_worker.rb, app/workers/slack/deploy_confirm_worker.rb, app/workers/slack/deploy_history_worker.rb, app/workers/slack/deploy_target_worker.rb, app/workers/slack/deploy_worker.rb, app/workers/slack/interaction_worker.rb, lib/genova/slack/interactive/bot.rb, lib/genova/slack/request_handler.rb, lib/genova/version.rb, spec/lib/genova/slack/request_handler_spec.rb, spec/workers/slack/interaction_worker_spec.rb
=> [#190] Add slack mention on error

app/workers/github/deploy_worker.rb
=> [#206] Fix undefined method error

Gemfile.lock, docker/base/Dockerfile
=> Fix mimemagic licensing issues

lib/genova/slack/block_kit/element_object.rb
=> [#221] Fix invalid blocks error

lib/genova/code_manager/git.rb, lib/genova/version.rb
=> Fix git tag error

lib/genova/ecs/client.rb, lib/genova/version.rb
=> Fix scheduled task option

Gemfile, Gemfile.lock, lib/genova/slack/block_kit/element_object.rb, lib/genova/version.rb
=> [#238] Truncate slack long text

Gemfile, Gemfile.lock, lib/genova/config/validator/deploy_config.json, lib/genova/ecs/client.rb, lib/genova/ecs/task/client.rb, lib/genova/version.rb
=> Add task overrides

lib/genova/ecs/task/client.rb
=> Improve task_overrides

app/api/v2/github_routes.rb, app/api/v2/slack_routes.rb, app/workers/github/deploy_worker.rb, app/workers/slack/interaction_worker.rb, config/settings.yml, lib/genova/exceptions.rb, lib/genova/run.rb, lib/genova/sidekiq/job_store.rb, lib/genova/version.rb, spec/api/v2/github_routes_spec.rb, spec/api/v2/slack_routes_spec.rb, spec/lib/genova/sidekiq/job_store_spec.rb, spec/workers/github/deploy_worker_spec.rb, spec/workers/slack/interaction_worker_spec.rb
=> Cancel double execution

lib/genova/ecs/task/client.rb, spec/lib/genova/ecs/task/client_spec.rb
=> Fix registered twice environment

config/environments/development.rb, config/environments/production.rb, lib/genova/slack/block_kit/helper.rb, lib/genova/slack/interactive/bot.rb
=> Fix invalid blocks

lib/autoloads/genova/deploy/workflow/runner.rb, lib/autoloads/genova/version.rb
=> Fix condition

lib/autoloads/genova/ecs/deployer/run_task/client.rb, lib/autoloads/genova/version.rb
https://github.com/metaps/genova/issues/343
=> Add raise run task error

app/controllers/workflows_controller.rb, lib/autoloads/genova/deploy/step/runner.rb
https://github.com/metaps/genova/issues/346
=> Support scheduled task step

app/controllers/deploy_jobs_controller.rb, app/javascript/entrypoints/application.scss, app/views/deploy_jobs/index.html.erb
https://github.com/metaps/genova/issues/359
=> Add search

app/workers/github/deploy_worker.rb, app/workers/slack/deploy_worker.rb, app/workers/slack/workflow_deploy_worker.rb, lib/autoloads/genova/deploy/step/runner.rb, lib/autoloads/genova/version.rb, spec/lib/autoloads/genova/deploy/step/runner_spec.rb, spec/workers/github/deploy_worker_spec.rb, spec/workers/slack/deploy_worker_spec.rb
https://github.com/metaps/genova/issues/361
=> Support stop step button

lib/autoloads/genova/code_manager/git.rb
https://github.com/metaps/genova/issues/308
=> Cannot lock ref
